image: gradle:latest

stages:
  - test
  - deploy

before_script:
  - apt-get -y install google-chrome-stable=102.0.5005.63


cache:
  key:
    files:
      - build.gradle.kts
  paths:
    - .gradle

variables:
  GRADLE_USER_HOME: '.gradle'

test:
  stage: test
  tags:
    - docker
  script:
    - ./gradlew clean runCITests -DultraPartnersUrl="https://ultrapartners.com" -DaffiliateLogin="kirillb@gmail.com" -Dpassword="123456"

deploy:
  stage: deploy
  script:
    - ./gradlew allureServe
  artifacts:
    when: always
    paths:
      - /allure-report